---
title: "Literature Review"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<p>
On how to tackle the listed objectives, some research was done from the previous VAST challenge that used the same dataset which was in 2014. Of the submissions found and analyzed, the submission conducted by [Kevin Griffin of University of California, Davis](https://www.cs.umd.edu/hcil/varepository/VAST%20Challenge%202014/challenges/MC2%20-%20Patterns%20of%20Life%20Analysis/entries/University%20of%20California,%20Davis/ "VAST Challenge Repository") was chosen as a good foundation on how to move forward.
</p>

<h2> What is Relevant for this Report? </h2>

<p>
What Griffin did was to analyze the movements of each employee and connect the dots to find meaningful insights relevant to the questions asked. However, Considering the number of employees tracked as well as the dates ranging up to 2 weeks with different times. It will be a challenging task to graph and analyze all movement in that way without a dynamic filtering system that could plot the movements, which is exactly what griffin did in his submission using a custom software. This method would be an ideal solution to the assignment’s 2nd objective if such a dynamic filtering is applicable in the required medium which is R markdown.
</p>

<p>
From the movement patterns, insights can also be obtained to how the employees’ relationships are with each other, relating to the 4th objective. While not discussed in the 2014 papers, the acquired information could then be built upon by incorporating a network graph to fully answer the objective.
</p>

<p>
As for the 3rd objective, the submission’s answer to how the author solved data inconsistencies can be used. The author decided to match the movements of employees with purchase data based on the time similarities. Such a way can also be done to answer this objective.
</p>

<h2> How to Adapt </h2>

<p>
This sub-section will mainly focus on how to do the second objective, which is the movement of employees.
</p>

<p>
While trying to individually analyze movements of employees is a step in a right direction, doing it in R would be a challenge. Griffin uses a custom-made software that is able to dynamically filter out data from the plot, while such an option is not available for R Markdown.
</p>

<p>
The thing that comes closest to this would be the library "crosstalk", which allows a more R shiny-like interaction to filter out data in plots. However, it is still an experimental library with the biggest downside of plotting everything in the dataframe first then filter out what is unneeded. Such a downside would be fine with a dataframe of 100 rows but not ~190000 rows which this project is dealing with.
</p>

<p>
Enter the submission from [University of Konstanz](https://www.youtube.com/watch?v=THLB7JKYThM&t=96s "YouTube"). What that team did was to instead reduce the data needed into points where the analysis will only look at the end points of each trip made by the employees. This reduction causes the analysis made from 190000 rows into ~2000, giving more ease into computation power. How to identify the start and end points will be explained in the [Methodology]() section.
</p>
